#
# Makefile for the sw_gpio .
#

# GPIO CORE
obj-$(CONFIG_NEW_GPIO)          += gpio_sw_core.o
obj-$(CONFIG_GPIO_SW_CLASS)     += gpio_sw_class.o
# GPIO Platform Drivers
obj-$(CONFIG_GPIO_SW)           += gpio_sw.o

obj-$(CONFIG_NEW_TEST_GPIO)          += gpio_test_sw_core.o
obj-$(CONFIG_GPIO_TEST_SW_CLASS)     += gpio_test_sw_class.o
# GPIO Platform Drivers
obj-$(CONFIG_GPIO_TEST_SW)           += gpio_test_sw.o